// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import mock "github.com/stretchr/testify/mock"

// Mailer is an autogenerated mock type for the Mailer type
type Mailer struct {
	mock.Mock
}

// SendMail provides a mock function with given fields: fromAddress, toAddress, subject, body, smtpHostPort, username, password
func (_m *Mailer) SendMail(fromAddress string, toAddress string, subject string, body string, smtpHostPort string, username string, password string) {
	_m.Called(fromAddress, toAddress, subject, body, smtpHostPort, username, password)
}
