// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Mailer is an autogenerated mock type for the Mailer type
type Mailer struct {
	mock.Mock
}

// SendMail provides a mock function with given fields: toAddress, subject, body
func (_m *Mailer) SendMail(toAddress string, subject string, body string) {
	_m.Called(toAddress, subject, body)
}
